# Используем официальный образ Python
FROM python:3.10-slim

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем файл с зависимостями
COPY requirements.txt .

# Устанавливаем зависимости
RUN pip install --no-cache-dir -r requirements.txt

# Копируем только необходимые папки
COPY inference/streamlit /app

# Создаем директорию для логов
RUN mkdir -p /app/logs/streamlit

# Открываем порт для Streamlit
EXPOSE 8501

# Запускаем приложение Streamlit
CMD ["streamlit", "run", "streamlit.py"]
